name: Add GitHub Sponsors to Readme
on:
  - pull_request
  - push
jobs:
  Deploy-to-Your-README-md:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3.0.2

      - name: List current folder location, files and show users GitHub token
        run: |
          pwd
          ls -a
          ls -a .github
          ls -a .github/workflows
          echo "Your GitHub secrets is ${{ secrets.GITHUB_TOKEN }}."

      - name: Generate Sponsors ğŸ’–
        uses: JamesIves/github-sponsors-readme-action@v1.0.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file: 'README.md'

      - name: Deploy to GitHub Pages ğŸš€
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main
          folder: '.'
